**Feature Engineering**

In [31]:
import numpy as np
import pandas as pd
from pathlib import Path

In [32]:
file_path = Path.cwd().parent.parent/"Data"/"Cleaned"/"Projects.csv"
df = pd.read_csv(file_path)
df

,Project_ID,Project_Name,Project_Type,Region,Start_Date,Planned_End_Date,Actual_End_Date,Planned_Budget_Cr,Actual_Cost_Cr,Planned_Progress_Pct,Actual_Progress_Pct,Contractor_ID,Status
0,P1001,Water Supply Project 1,Water Supply,Central,2025-12-13,2026-10-20,2026-10-30,140.97,146.36,100,100,C104,Completed
1,P1002,Tunnel Project 2,Tunnel,Northeast,2022-11-30,2024-08-10,NaN,128.71,128.97,55,59,C106,Ongoing
2,P1003,Metro Project 3,Metro,West,2023-07-07,2025-12-18,2026-02-27,152.97,154.98,100,75,C107,Delayed
3,P1004,Airport Project 4,Airport,North,2025-03-07,2026-09-20,2026-12-19,76.05,78.31,100,100,C104,Completed
4,P1005,Airport Project 5,Airport,Northeast,2024-05-27,2026-09-11,NaN,179.54,197.38,49,53,C110,Ongoing
...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,P1248,Highway Project 248,Highway,South,2024-04-25,2025-12-18,NaN,107.89,120.16,43,35,C109,Ongoing
248,P1249,Power Project 249,Power,Northeast,2023-04-30,2024-10-19,2024-11-23,167.28,161.79,100,100,C103,Completed
249,P1250,Railway Project 250,Railway,North,2022-10-06,2025-01-21,2025-01-21,36.27,45.77,100,100,C104,Completed
250,P1251,Bridge Project 99,Bridge,Central,2023-03-12,2024-04-13,2024-06-24,68.22,67.32,100,61,C109,Delayed
251,P1252,Bridge Project 122,Bridge,Northeast,2022-09-13,2024-02-26,2024-03-02,54.92,68.27,100,100,C109,Completed

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Project_ID            252 non-null    object
 1   Project_Name          249 non-null    object
 2   Project_Type          252 non-null    object
 3   Region                252 non-null    object
 4   Start_Date            246 non-null    object
 5   Planned_End_Date      252 non-null    object
 6   Actual_End_Date       140 non-null    object
 7   Planned_Budget_Cr     252 non-null    float64
 8   Actual_Cost_Cr        252 non-null    float64
 9   Planned_Progress_Pct  252 non-null    int64
 10  Actual_Progress_Pct   252 non-null    int64
 11  Contractor_ID         249 non-null    object
 12  Status                252 non-null    object
dtypes: float64(2), int64(2), object(9)
memory usage: 25.7+ KB

In [34]:
date_col = ["Start_Date", "Planned_End_Date", "Actual_End_Date"]
for col in date_col:
    df[col] = pd.to_datetime(df[col], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Project_ID            252 non-null    object
 1   Project_Name          249 non-null    object
 2   Project_Type          252 non-null    object
 3   Region                252 non-null    object
 4   Start_Date            246 non-null    datetime64[ns]
 5   Planned_End_Date      252 non-null    datetime64[ns]
 6   Actual_End_Date       140 non-null    datetime64[ns]
 7   Planned_Budget_Cr     252 non-null    float64
 8   Actual_Cost_Cr        252 non-null    float64
 9   Planned_Progress_Pct  252 non-null    int64
 10  Actual_Progress_Pct   252 non-null    int64
 11  Contractor_ID         249 non-null    object
 12  Status                252 non-null    object
dtypes: datetime64[ns](3), float64(2), int64(2), object(6)
memory usage: 25.7+ KB

In [35]:
df["Cost_Overrun"] = round((df["Actual_Cost_Cr"]-df["Planned_Budget_Cr"]), 2)
df["Cost_Overrun_Status"] = np.select(
    [
        df["Cost_Overrun"] < 0,
        df["Cost_Overrun"] == 0,
        df["Cost_Overrun"] > 0
    ],
    [
        "Under Budget",
        "Exact Budget",
        "Exceeding Budget"
    ], default = "Not Available"
)

In [36]:
df["Progress_Gap"] = (df["Actual_Progress_Pct"]-df["Planned_Progress_Pct"])
df["Progress_Risk"] = np.select(
    [
        df["Progress_Gap"] < -20,
        df["Progress_Gap"] < -10,
        df["Progress_Gap"] < 0
    ],
    [
        "Critical",
        "High",
        "Medium"
    ],
    default="Low"
)

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Project_ID            252 non-null    object
 1   Project_Name          249 non-null    object
 2   Project_Type          252 non-null    object
 3   Region                252 non-null    object
 4   Start_Date            246 non-null    datetime64[ns]
 5   Planned_End_Date      252 non-null    datetime64[ns]
 6   Actual_End_Date       140 non-null    datetime64[ns]
 7   Planned_Budget_Cr     252 non-null    float64
 8   Actual_Cost_Cr        252 non-null    float64
 9   Planned_Progress_Pct  252 non-null    int64
 10  Actual_Progress_Pct   252 non-null    int64
 11  Contractor_ID         249 non-null    object
 12  Status                252 non-null    object
 13  Cost_Overrun          252 non-null    float64
 14  Cost_Overrun_Status   252 non-null    object
 15  Progress_Gap          252 non-null    int64
 16  Progress_Risk         252 non-null    object
dtypes: datetime64[ns](3), float64(3), int64(3), object(8)
memory usage: 33.6+ KB

In [38]:
df

,Project_ID,Project_Name,Project_Type,Region,Start_Date,Planned_End_Date,Actual_End_Date,Planned_Budget_Cr,Actual_Cost_Cr,Planned_Progress_Pct,Actual_Progress_Pct,Contractor_ID,Status,Cost_Overrun,Cost_Overrun_Status,Progress_Gap,Progress_Risk
0,P1001,Water Supply Project 1,Water Supply,Central,2025-12-13,2026-10-20,2026-10-30,140.97,146.36,100,100,C104,Completed,5.39,Exceeding Budget,0,Low
1,P1002,Tunnel Project 2,Tunnel,Northeast,2022-11-30,2024-08-10,NaT,128.71,128.97,55,59,C106,Ongoing,0.26,Exceeding Budget,4,Low
2,P1003,Metro Project 3,Metro,West,2023-07-07,2025-12-18,2026-02-27,152.97,154.98,100,75,C107,Delayed,2.01,Exceeding Budget,-25,Critical
3,P1004,Airport Project 4,Airport,North,2025-03-07,2026-09-20,2026-12-19,76.05,78.31,100,100,C104,Completed,2.26,Exceeding Budget,0,Low
4,P1005,Airport Project 5,Airport,Northeast,2024-05-27,2026-09-11,NaT,179.54,197.38,49,53,C110,Ongoing,17.84,Exceeding Budget,4,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,P1248,Highway Project 248,Highway,South,2024-04-25,2025-12-18,NaT,107.89,120.16,43,35,C109,Ongoing,12.27,Exceeding Budget,-8,Medium
248,P1249,Power Project 249,Power,Northeast,2023-04-30,2024-10-19,2024-11-23,167.28,161.79,100,100,C103,Completed,-5.49,Under Budget,0,Low
249,P1250,Railway Project 250,Railway,North,2022-10-06,2025-01-21,2025-01-21,36.27,45.77,100,100,C104,Completed,9.50,Exceeding Budget,0,Low
250,P1251,Bridge Project 99,Bridge,Central,2023-03-12,2024-04-13,2024-06-24,68.22,67.32,100,61,C109,Delayed,-0.90,Under Budget,-39,Critical
251,P1252,Bridge Project 122,Bridge,Northeast,2022-09-13,2024-02-26,2024-03-02,54.92,68.27,100,100,C109,Completed,13.35,Exceeding Budget,0,Low

In [39]:
df.to_csv("../../Data/Processed/Projects.csv", index=False)