**Contractors**

In [25]:
import numpy as np
import pandas as pd
from pathlib import Path

In [26]:
file_path = Path.cwd().parent.parent/"Data"/"Cleaned"/"Contractors.csv"
df = pd.read_csv(file_path)
df

,Contractor_ID,Contractor_Name,Experience_Years,Projects_Completed,Average_Delay_Days,Performance_Rating
0,C101,Buildmax Infra,25,22,5,4.3
1,C102,Roadworks India,12,36,8,4.2
2,C103,Apex Constructions,26,19,18,3.5
3,C104,NaN,5,19,8,3.0
4,C105,Metrobuild Pvt Ltd,24,11,18,5.8
5,C106,National Infraworks,25,61,8,3.5
6,C107,Prime Engineering,13,8,30,4.4
7,C108,Vertex Construction,27,62,12,3.1
8,C109,Horizon Developers,11,51,5,2.6
9,C110,Urbangrid Infra,16,53,30,3.3
10,C111,Suryodaya Projects,13,13,22,3.5
11,C112,Bluestone Engineering,8,56,5,3.8

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Contractor_ID       12 non-null     object
 1   Contractor_Name     11 non-null     object
 2   Experience_Years    12 non-null     int64
 3   Projects_Completed  12 non-null     int64
 4   Average_Delay_Days  12 non-null     int64
 5   Performance_Rating  12 non-null     float64
dtypes: float64(1), int64(3), object(2)
memory usage: 708.0+ bytes

In [28]:
df["Performance_Category"] = np.select(
    [
        df["Performance_Rating"] >= 4.5,
        df["Performance_Rating"] >= 3.5,
        df["Performance_Rating"] >= 2.5
    ],
    [
        "Excellent",
        "Good",
        "Average"
    ],
    default="Poor"
)

In [29]:
df["Average_Delay_Days"]

0      5
1      8
2     18
3      8
4     18
5      8
6     30
7     12
8      5
9     30
10    22
11     5
Name: Average_Delay_Days, dtype: int64

In [30]:
df["Experience_Category"] = np.select(
    [
        df["Experience_Years"] >= 20,
        df["Experience_Years"] >= 15,
        df["Experience_Years"] >= 10
    ],
    [
        "High Experienced",
        "Good Experience",
        "Average Experience"
    ],
    default="Beginner"
)

In [31]:
df["Delay_Category"] = np.select(
    [
        df["Average_Delay_Days"] >= 25,
        df["Average_Delay_Days"] >= 10
    ],
    [
        "High Delay",
        "Medium Delay"
    ],
    default="Low Delay"
)

In [32]:
df

,Contractor_ID,Contractor_Name,Experience_Years,Projects_Completed,Average_Delay_Days,Performance_Rating,Performance_Category,Experience_Category,Delay_Category
0,C101,Buildmax Infra,25,22,5,4.3,Good,High Experienced,Low Delay
1,C102,Roadworks India,12,36,8,4.2,Good,Average Experience,Low Delay
2,C103,Apex Constructions,26,19,18,3.5,Good,High Experienced,Medium Delay
3,C104,NaN,5,19,8,3.0,Average,Beginner,Low Delay
4,C105,Metrobuild Pvt Ltd,24,11,18,5.8,Excellent,High Experienced,Medium Delay
5,C106,National Infraworks,25,61,8,3.5,Good,High Experienced,Low Delay
6,C107,Prime Engineering,13,8,30,4.4,Good,Average Experience,High Delay
7,C108,Vertex Construction,27,62,12,3.1,Average,High Experienced,Medium Delay
8,C109,Horizon Developers,11,51,5,2.6,Average,Average Experience,Low Delay
9,C110,Urbangrid Infra,16,53,30,3.3,Average,Good Experience,High Delay
10,C111,Suryodaya Projects,13,13,22,3.5,Good,Average Experience,Medium Delay
11,C112,Bluestone Engineering,8,56,5,3.8,Good,Beginner,Low Delay

In [33]:
df.to_csv("../../Data/Processed/Contractors.csv", index=False)